version: 2.0
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: copy to s3
          command: aws s3 sync static-site/ s3://mperreux --delete
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
